INSERT INTO PUBLIC.GENRE (name) VALUES('Комедия');
INSERT INTO PUBLIC.GENRE (name) VALUES('Драма');
INSERT INTO PUBLIC.GENRE (name) VALUES('Мультфильм');
INSERT INTO PUBLIC.GENRE (name) VALUES('Триллер');
INSERT INTO PUBLIC.GENRE (name) VALUES('Документальный');
INSERT INTO PUBLIC.GENRE (name) VALUES('Боевик');

INSERT INTO PUBLIC.RATING (name) VALUES('G');
INSERT INTO PUBLIC.RATING (name) VALUES('PG');
INSERT INTO PUBLIC.RATING (name) VALUES('PG-13');
INSERT INTO PUBLIC.RATING (name) VALUES('R');
INSERT INTO PUBLIC.RATING (name) VALUES('NC-17');

